version: '3'

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=production
      - DB_CONNECTION=pgsql
      - DB_HOST=DB_HOST=dpg-cucumqqn91rc73elfrr0-a.oregon-postgres.render.com
      - DB_PORT=5432
      - DB_DATABASE=bd_web_iln6
      - DB_USERNAME=bd_web_iln6_user
      - DB_PASSWORD=qxsIcJgMJPdKP991UKdX5sDTk6DzbAhz

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=your_database_name
      - POSTGRES_USER=your_database_user
      - POSTGRES_PASSWORD=your_database_password
    ports:
      - "5432:5432"
